# guardian-manager/wrangler.toml
# Cloudflare Pages Functions - Bindings Only

[vars]
BUNGIE_CLIENT_ID = "51042"
BUNGIE_API_KEY = "18745be24a1c4b7bb0a5741eb4f2f6c2"
BUNGIE_AUTH_URL = "https://www.bungie.net/en/OAuth/Authorize"

[[kv_namespaces]]
binding = "guardian_kv"
id = "a0e4b35ad4694542a88d447836f6891d"

[[d1_databases]]
binding = "guardian_db"
database_name = "guardian-db"
database_id = "9784d2e2-ca80-495c-986d-28ca84e1dc87"